use_frameworks!

platform :ios, '11.0'

target 'ComposableDataSource_Example' do
  pod 'ComposableDataSource', :path => '../'
  pod 'Celestial'

  target 'ComposableDataSource_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
